massive changes

diff --git a/install b/install
--- a/install
+++ b/install
@@ -1,97 +1,52 @@
-#!/bin/bash
+#!/usr/bin/env zsh
 # A script for installing dependencies and setting up needed Symbolic Links
 # Created by Jeremy Winterberg
-# Updated 07/23/2015
+# Updated 08/14/2017
 # NOTICE: Modify script to your own preferences! This mostly uses default
 #         locations, but can be changed to whatever you need.
 
-# Check if ZSH is installed
-hash zsh 2>/dev/null || { 
-    echo >&2 "ZSH Not installed. Installing oh-my-zsh while we're at it!"; 
-    curl -L https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh | sh
-    chmod -s /bin/zsh
-    echo >&2 "ZSH is now installed and set as your default shell!"; 
-    zsh
-}
 
-# Check if Git is installed
-hash git 2>/dev/null || {
-    echo >&2 "git not installed. Taking care of that for you!";
-    case $(uname) in
-        OpenBSD)
-            sudo pkg_add git
-            ;;
-        FreeBSD)
-            cd /usr/ports/devel/git
-            sudo make install
-            ;;
-        Linux)
-            if [ head -n10 /etc/*-release | grep -i "ubuntu" ]
-            then
-                sudo apt-get install git
-                sudo apt-get install silversearcher-ag
-            elif [ head -n10 /etc/*-release | grep -i "arch" ]
-            then
-                sudo pacman -S git
-            elif [ head -n10 /etc/*-release | grep -i "fedora" ]
-            then
-                sudo yum install git
-            elif [ head -n10 /etc/*-release | grep -i "gentoo" ]
-            then
-                emerge --ask --verbose dev-vcs/git
-            elif [ head -n10 /etc/*-release | grep -i "openSUSE" ]
-            then
-                sudo zypper install git
-            fi
-            ;;
-        Darwin)
-            hash brew 2>/dev/null || {
-                echo "You do not have homebrew installed, taking care of that!"
-                ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
-                brew update
-                brew doctor
-                brew install git
-                brew install vim
-                brew install tmux
-                brew install reattach-to-user-namespace
-                brew install the_silver_searcher
-            }
-            brew install git
-            ;;
-    esac
-}
+# Fancy ls script taken from github.com/brandonroehl/dotfiles
+if [ hash brew >/dev/null 2>&1 ]
+then
+  echo 'Attempting to install brew'
+  if [ uname = "Darwin" ]
+  then
+    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
+  else
+    sudo apt-get install build-essential curl git python-setuptools ruby
+    ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install)"
+  fi
+fi
+brew install zsh git coreutils vim tmux wget bash the_silver_searcher reattach-to-user-namespace
 
 # Check if Oh My ZSH is installed
-if [ -d "$HOME/.oh-my-zsh/" ]; then
-    ln -sv ~/.dotfiles/aliases.zsh  ~/.oh-my-zsh/custom/aliases.zsh
-else
-    echo >&2 "oh-my-zsh is not installed, installing...";
-    curl -L https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh | sh
-    ln -sv ~/.dotfiles/aliases.zsh  ~/.oh-my-zsh/custom/aliases.zsh
+if ! [ -d "$HOME/.oh-my-zsh/" ]; then
+  echo >&2 "oh-my-zsh is not installed, fixing that...";
+  curl -L https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh | sh
 fi
 
-# Check if the Ultimate VimRC is installed
-if [ -d "$HOME/.vim_runtime/" ]; then
-    ln -sv ~/.dotfiles/my_configs.vim ~/.vim_runtime/
-else
-    echo >&2 "Ultimate Vim RC not found. installing...";
-    git clone git://github.com/amix/vimrc.git ~/.vim_runtime
-    sh ~/.vim_runtime/install_awesome_vimrc.sh
-    ln -sv ~/.dotfiles/my_configs.vim ~/.vim_runtime/
-    git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim_runtime/sources_non_forked/vundle
-    vim +PluginInstall +qall
+echo 'install rvm or upgrade rvm'
+curl -sSL https://get.rvm.io | bash -s stable
+if [ hash rvm >/dev/null 2>&1 ]
+then
+  rvm cleanup all
 fi
 
-# Make symlinks to home directory for common files
-ln -sv ~/.dotfiles/agignore ~/.agignore
-ln -sv ~/.dotfiles/gitconfig ~/.gitconfig
-ln -sv ~/.dotfiles/gitignore ~/.gitignore
-ln -sv ~/.dotfiles/gitmessage ~/.gitmessage
-ln -sv ~/.dotfiles/gemrc ~/.gemrc
-ln -sv ~/.dotfiles/rspec ~/.rspec
-ln -sv ~/.dotfiles/zshrc ~/.zshrc
-ln -sv ~/.dotfiles/tmux.conf ~/.tmux.conf
-ln -sv ~/.dotfiles/tmux-dev.sh ~/.tmux-dev.sh
-if [ "$(uname)" = "Darwin" ]; then
-    ln -sv ~/.dotfiles/tmux-osx.conf ~/.tmux-osx
-fi
+git submodule init
+git submodule update --recursive
+
+files=( 'vimrc' 'vim' 'zshrc' 'zsh' 'tmux.conf' 'tmux-dev.sh' 'tmux-osx' 'agignore' 'gitconfig' 'gitignore' 'gitmessage' 'gemrc' 'rspec' )
+for file in $files
+do
+  echo ""
+  echo "Simlinking $file to $HOME"
+  ln -sf "$PWD/$file" "$HOME/.$file"
+  if [ $? -eq 0 ]
+  then
+    echo "$PWD/$file ~> $HOME/.$file"
+  else
+    echo 'Install failed to symlink.'
+    exit 1
+  fi
+done
